// Generates ../rooms.gen.asm from LAYOUT.md + actors.ts. Run: npx tsx games/blackbox/tools/gen.ts
// test/blackbox/ checks that the committed file is up to date.
import { writeFileSync } from 'node:fs';
import { ACTORS } from './actors';
import { H, W, parseLayout, type LayoutRoom } from './layout';

/** Tile codes held in the RAM room buffer (one per LAYOUT character class). */
export const TILE: Record<string, number> = {
  '.': 0, '@': 0, i: 0, g: 0, d: 0, h: 0, u: 0, p: 0, a: 0, n: 0, b: 0,
  '#': 1, S: 3, C: 4, '=': 5, '+': 6, D: 7, V: 8, T: 9, E: 10, L: 11, K: 12,
};
export const TILE_NAMES = ['FLOOR', 'WALL', 'WALLFACE', 'SHELF', 'CAMERA', 'DESK', 'DOOR', 'LOCKED', 'VENT', 'TERMINAL', 'CHARGER', 'LIFT', 'CABLE'];
export const OBJ: Record<string, number> = { g: 1, d: 2, h: 3, u: 4, p: 5, a: 6, n: 7, b: 8, i: 9, C: 10 };
export const OBJ_NAMES = ['', 'GUARD', 'DRONE', 'HEAVY', 'HUNTER', 'PROTO', 'AGENT', 'NPC', 'BOSS', 'PICKUP', 'CAMERA'];
const MODE: Record<string, number> = { h: 0, v: 1, t: 2, sq: 3 };
const NONE = 255;
const END = 254;

export const label = (id: string) => id.replace('.', '_');

export function flagNames(rooms: LayoutRoom[]): string[] {
  const out: string[] = [];
  const add = (f: string) => {
    if (!out.includes(f)) out.push(f);
  };
  for (const r of rooms) {
    for (const g of r.gives) add(g.flag);
    for (const f of r.locks.values()) add(f);
    if (r.warp?.flag) add(r.warp.flag);
  }
  return out;
}

export function rle(grid: string[]): number[] {
  const codes = grid.join('').split('').map((c) => {
    const t = TILE[c];
    if (t === undefined) throw new Error(`no tile code for '${c}'`);
    return t;
  });
  const out: number[] = [];
  for (let i = 0; i < codes.length; ) {
    let n = 1;
    while (n < 16 && i + n < codes.length && codes[i + n] === codes[i]) n++;
    out.push(((n - 1) << 4) | codes[i]!);
    i += n;
  }
  return out;
}

export function objects(r: LayoutRoom): number[][] {
  const out: number[][] = [];
  r.grid.forEach((row, y) =>
    [...row].forEach((ch, x) => {
      const type = OBJ[ch];
      if (!type) return;
      const spec = ACTORS[`${r.id} ${x},${y}`];
      if (!spec) throw new Error(`actors.ts: no entry for '${ch}' at ${r.id} ${x},${y}`);
      let a = 0;
      let b = 0;
      let c = 0;
      if (ch === 'g' || ch === 'h' || ch === 'd') {
        a = MODE[spec.mode ?? 'h']!;
        if (spec.mode === 't') [b, c] = [spec.dir2 ?? 0, Math.round((spec.period ?? 180) / 15)];
        else if (spec.mode === 'sq') [b, c] = [spec.size ?? 2, 0];
        else [b, c] = [spec.min ?? 0, spec.max ?? 15];
      } else if (ch === 'u') a = spec.range ?? 4;
      else if (ch === 'p') a = spec.active ?? 0;
      else if (ch === 'n' || ch === 'b' || ch === 'i') a = spec.id ?? 0;
      out.push([type, x, y, spec.dir ?? 0, a, b, c]);
    }),
  );
  return out;
}

function arrival(r: LayoutRoom): [number, number] {
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (r.grid[y]![x] === '@') return [x, y];
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      if (r.grid[y]![x] !== 'L') continue;
      for (const [dx, dy] of [[0, 1], [0, -1], [-1, 0], [1, 0]] as const) {
        const c = r.grid[y + dy]?.[x + dx];
        if (c !== undefined && TILE[c] === 0) return [x + dx, y + dy];
      }
    }
  return [NONE, NONE];
}

export function generate(): string {
  const rooms = parseLayout();
  const index = new Map(rooms.map((r, i) => [r.id, i]));
  const flags = flagNames(rooms);
  const L: string[] = [];
  L.push('; GENERATED by games/blackbox/tools/gen.ts from LAYOUT.md and tools/actors.ts — do not edit.', '');
  L.push(`NUM_ROOMS = ${rooms.length}`, `ROOM_REC = 20`, `EXIT_NONE = ${NONE}`, `EXIT_END = ${END}`, `RLE_TILES = ${W * H}`);
  rooms.forEach((r, i) => L.push(`R_${label(r.id)} = ${i}`));
  L.push('', '; layout flags (scripts define more after NUM_LAYOUT_FLAGS)');
  flags.forEach((f, i) => L.push(`F_${f} = ${i}`));
  L.push(`NUM_LAYOUT_FLAGS = ${flags.length}`, '', '; tile codes');
  TILE_NAMES.forEach((n, i) => L.push(`T_${n} = ${i}`));
  L.push('', '; object types (record: type, x, y, dir, a, b, c)');
  OBJ_NAMES.forEach((n, i) => i && L.push(`O_${n} = ${i}`));
  L.push('OBJ_REC = 7', '', '.data', 'room_table:');
  const exitOf = (r: LayoutRoom, side: string) => {
    const e = r.exits.find((x) => x.side === side);
    return e ? (e.to === 'END' ? END : index.get(e.to)!) : NONE;
  };
  const lockOf = (r: LayoutRoom, side: string) => {
    const f = r.locks.get(side);
    return f ? `F_${f}` : NONE;
  };
  for (const r of rooms) {
    const [ax, ay] = arrival(r);
    const warp = r.warp ? (r.warp.to === 'END' ? END : index.get(r.warp.to)!) : NONE;
    const zone = Number(r.id.split('.')[0]);
    const tileset = [0, 0, 0, 1, 1, 2, 3, 3][zone]!;
    L.push(
      `    .word rle_${label(r.id)}                 ; ${r.id} ${r.name}`,
      `    .byte ${['N', 'S', 'E', 'W'].map((s) => exitOf(r, s)).join(', ')}, ${['N', 'S', 'E', 'W'].map((s) => lockOf(r, s)).join(', ')}`,
      `    .byte ${warp}, ${r.warp?.flag ? `F_${r.warp.flag}` : NONE}, ${zone}, ${tileset}, ${ax}, ${ay}`,
      `    .word objs_${label(r.id)}, trig_${label(r.id)}`,
    );
  }
  for (const r of rooms) {
    const bytes = rle(r.grid);
    L.push(`rle_${label(r.id)}:   ; ${bytes.length} bytes`);
    for (let i = 0; i < bytes.length; i += 16) L.push(`    .byte ${bytes.slice(i, i + 16).join(', ')}`);
    const objs = objects(r);
    L.push(`objs_${label(r.id)}:`, `    .byte ${objs.length}`);
    for (const o of objs) L.push(`    .byte ${o.join(', ')}`);
  }
  return L.join('\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = new URL('../rooms.gen.asm', import.meta.url);
  writeFileSync(out, generate());
  console.log(`wrote ${out.pathname}`);
}
