// Generates ../tiles.gen.asm: one tileset per zone group, drawn once with symbolic colours
// (p main, q dark, r light, s accent, t accent 2) and recoloured per tileset. Also the tile attribute table.
// Run: npx tsx games/blackbox/tools/tiles.ts
import { writeFileSync } from 'node:fs';
import { TILE_NAMES } from './gen';

// order = tile codes 1..12 (code 0 = floor is never drawn; the floor is the CLS colour)
const ART: Record<string, string[]> = {
  WALL: ['qqqqqqqq', 'qqqqqqqq', 'qqqpqqqq', 'qqqqqqqq', 'qqqqqqqq', 'qqqqqqpq', 'qqqqqqqq', 'qqqqqqqq'],
  WALLFACE: ['qqqqqqqq', 'rrrrrrrr', 'pppppppp', 'pppppppp', 'pppqpppp', 'pppppppp', 'pppppppp', 'qqqqqqqq'],
  SHELF: ['qqqqqqqq', 'qsstsstq', 'qqqqqqqq', 'qtsstssq', 'qqqqqqqq', 'qstsstsq', 'qqqqqqqq', 'qqqqqqqq'],
  CAMERA: ['qqqqqqqq', 'qqppppqq', 'qprrrrpq', 'qpr66rpq', 'qprrrrpq', 'qqppppqq', 'qqqppqqq', 'qqqqqqqq'],
  DESK: ['........', '44444444', '49999994', '49999994', '49999994', '44444444', '4......4', '........'],
  DOOR: ['q......q', 'q......q', 'q......q', 'q......q', 'q......q', 'q......q', 'q......q', 'q......q'],
  LOCKED: ['qqqqqqqq', 'q666666q', 'q6.66.6q', 'q666666q', 'q66ee66q', 'q666666q', 'q666666q', 'qqqqqqqq'],
  VENT: ['qqqqqqqq', 'q3r3r3rq', 'q3r3r3rq', 'q3r3r3rq', 'q3r3r3rq', 'q3r3r3rq', 'q3r3r3rq', 'qqqqqqqq'],
  TERMINAL: ['33333333', '30000003', '30bb0b03', '30b0bb03', '30000003', '33333333', '.373373.', '.777777.'],
  CHARGER: ['.888888.', '8dddddd8', '8d8888d8', '8d8ee8d8', '8d8888d8', '8dddddd8', '.888888.', '........'],
  LIFT: ['77777777', '7aaaaaa7', '7a7aa7a7', '7a7aa7a7', '7a7aa7a7', '7a7aa7a7', '7aaaaaa7', '77777777'],
  CABLE: ['........', '..eeee..', '.e....e.', '.e.33.e.', '.e.33.e.', '..e..e..', '...ee...', '....e...'],
};

/** Per tileset: floor colour and the symbolic colours p q r s t (hex digits of the DawnBringer-16 palette). */
const SETS = [
  { name: 'OFFICE', floor: 1, p: '7', q: '3', r: 'a', s: '8', t: 'c' }, // zones 0-2
  { name: 'SECURITY', floor: 3, p: 'a', q: '7', r: 'f', s: 'd', t: 'b' }, // zones 3-4
  { name: 'BUNKER', floor: 3, p: '7', q: '4', r: 'c', s: '9', t: 'e' }, // zone 5
  { name: 'SERVER', floor: 0, p: '8', q: '2', r: 'd', s: 'b', t: '6' }, // zones 6-7
];

// SOLID = blocks walking, OPAQUE = blocks sight, USE = can be used with A (LAYOUT.md legend)
const ATTR: Record<string, number> = {
  FLOOR: 0, WALL: 3, WALLFACE: 3, SHELF: 3, CAMERA: 3, DESK: 1, DOOR: 0, LOCKED: 3, VENT: 2, TERMINAL: 5, CHARGER: 5, LIFT: 7, CABLE: 5,
};

export function generateTiles(): string {
  const L = ['; GENERATED by games/blackbox/tools/tiles.ts — do not edit.', '', 'A_SOLID = 1', 'A_OPAQUE = 2', 'A_USE = 4', `NUM_TILESETS = ${SETS.length}`, '', '.data', 'tile_attr:'];
  L.push(`    .byte ${TILE_NAMES.map((n) => ATTR[n]).join(', ')}`);
  L.push('floor_colors:', `    .byte ${SETS.map((s) => s.floor).join(', ')}`);
  L.push('tileset_ptrs:', `    .word ${SETS.map((s) => `tiles_${s.name} - 32`).join(', ')}`);
  for (const set of SETS) {
    L.push(`tiles_${set.name}:`);
    for (const name of TILE_NAMES.slice(1)) {
      L.push(`.sprite   ; ${name}`);
      for (const row of ART[name]!) {
        const out = row.replace(/[pqrst]/g, (c) => (set as unknown as Record<string, string>)[c]!);
        if (!/^[.0-9a-f]{8}$/.test(out)) throw new Error(`bad row ${row} -> ${out}`);
        L.push(`    ${out}`);
      }
    }
  }
  return L.join('\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = new URL('../tiles.gen.asm', import.meta.url);
  writeFileSync(out, generateTiles());
  console.log(`wrote ${out.pathname}`);
}
