import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';

// `npm run bench:scan` — a measurement, not an acceptance test: time for the real web scanner to receive
// a 50 KB cartridge from a fake camera playing its looping QR animation (K = 196, 294 frames, 150 ms each).
// Headless Chromium on the build machine; the fake camera delivers every frame cleanly (no loss model).
test('50 KB cartridge through the browser scanner (fake camera)', async ({ page }) => {
  await page.goto('./?test');
  await page.click('#nav-scan');
  const t0 = Date.now();
  await expect(page.locator('#scan-play')).toBeVisible({ timeout: 170_000 });
  const seconds = (Date.now() - t0) / 1000;
  const detail = await page.locator('#scan-detail').textContent();
  const status = await page.locator('#scan-status').textContent();
  const md = `# Browser scan measurement (fake camera)

Generated by \`npm run bench:scan\`. Headless Chromium (Playwright) on the build machine, fake camera
playing a 640×480 .y4m made from the looping QR GIF of a 50 KB cartridge (v12-M, 150 ms/frame,
4 px/module). The fake camera is clean: this measures the scanner pipeline (camera → worker/zxing →
fountain → verify → IndexedDB), not optical robustness. Not a phone.

- Result: ${status}
- Time from pressing Scan to verified cartridge: **${seconds.toFixed(1)} s** (${((50 * 1024) / 1024 / seconds).toFixed(2)} KB/s)
- Scanner stats: ${detail}
- Reference: one loop of the GIF is 294 frames × 150 ms = 44.1 s; the source blocks alone take 196 × 150 ms = 29.4 s.
`;
  writeFileSync(join(import.meta.dirname, '../bench/scan.md'), md);
  console.log(md);
});
