// Writes font.gen.asm for the mockup: the bubble font (5x6 letters with room for Å Ä Ö above, 1 bit per pixel,
// 8 bytes per glyph) plus the mockup's bubble lines and labels encoded as glyph indices (255 ends a string).
// Run: npx tsx games/bo/mockup/gen.ts
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const E = '.....';
/** an ordinary glyph: rows 0-1 empty (room for diacritics), body in rows 2-7 */
const body = (rows: string[]) => [E, E, ...rows];

const GLYPHS: Record<string, string[]> = {
  ' ': body([E, E, E, E, E, E]),
  A: body(['.###.', '#...#', '#...#', '#####', '#...#', '#...#']),
  B: body(['####.', '#...#', '####.', '#...#', '#...#', '####.']),
  C: body(['.###.', '#...#', '#....', '#....', '#...#', '.###.']),
  D: body(['####.', '#...#', '#...#', '#...#', '#...#', '####.']),
  E: body(['#####', '#....', '####.', '#....', '#....', '#####']),
  F: body(['#####', '#....', '####.', '#....', '#....', '#....']),
  G: body(['.###.', '#....', '#.###', '#...#', '#...#', '.###.']),
  H: body(['#...#', '#...#', '#####', '#...#', '#...#', '#...#']),
  I: body(['.###.', '..#..', '..#..', '..#..', '..#..', '.###.']),
  J: body(['..###', '...#.', '...#.', '...#.', '#..#.', '.##..']),
  K: body(['#...#', '#..#.', '###..', '#..#.', '#...#', '#...#']),
  L: body(['#....', '#....', '#....', '#....', '#....', '#####']),
  M: body(['#...#', '##.##', '#.#.#', '#...#', '#...#', '#...#']),
  N: body(['#...#', '##..#', '#.#.#', '#..##', '#...#', '#...#']),
  O: body(['.###.', '#...#', '#...#', '#...#', '#...#', '.###.']),
  P: body(['####.', '#...#', '#...#', '####.', '#....', '#....']),
  Q: body(['.###.', '#...#', '#...#', '#.#.#', '#..#.', '.##.#']),
  R: body(['####.', '#...#', '#...#', '####.', '#..#.', '#...#']),
  S: body(['.####', '#....', '.###.', '....#', '....#', '####.']),
  T: body(['#####', '..#..', '..#..', '..#..', '..#..', '..#..']),
  U: body(['#...#', '#...#', '#...#', '#...#', '#...#', '.###.']),
  V: body(['#...#', '#...#', '#...#', '#...#', '.#.#.', '..#..']),
  W: body(['#...#', '#...#', '#...#', '#.#.#', '##.##', '#...#']),
  X: body(['#...#', '.#.#.', '..#..', '..#..', '.#.#.', '#...#']),
  Y: body(['#...#', '#...#', '.#.#.', '..#..', '..#..', '..#..']),
  Z: body(['#####', '...#.', '..#..', '.#...', '#....', '#####']),
  // Swedish letters: the diacritic in rows 0-2, a 5-row body in rows 3-7
  'Å': ['..#..', '.#.#.', '..#..', '.###.', '#...#', '#####', '#...#', '#...#'],
  'Ä': [E, '.#.#.', E, '.###.', '#...#', '#####', '#...#', '#...#'],
  'Ö': [E, '.#.#.', E, '.###.', '#...#', '#...#', '#...#', '.###.'],
  '0': body(['.###.', '#..##', '#.#.#', '##..#', '#...#', '.###.']),
  '1': body(['..#..', '.##..', '..#..', '..#..', '..#..', '.###.']),
  '2': body(['.###.', '#...#', '...#.', '..#..', '.#...', '#####']),
  '3': body(['####.', '....#', '.###.', '....#', '....#', '####.']),
  '4': body(['...#.', '..##.', '.#.#.', '#####', '...#.', '...#.']),
  '5': body(['#####', '#....', '####.', '....#', '....#', '####.']),
  '6': body(['.###.', '#....', '####.', '#...#', '#...#', '.###.']),
  '7': body(['#####', '....#', '...#.', '..#..', '..#..', '..#..']),
  '8': body(['.###.', '#...#', '.###.', '#...#', '#...#', '.###.']),
  '9': body(['.###.', '#...#', '#...#', '.####', '....#', '.###.']),
  '!': body(['..#..', '..#..', '..#..', '..#..', E, '..#..']),
  '?': body(['.###.', '#...#', '...#.', '..#..', E, '..#..']),
  '.': body([E, E, E, E, E, '..#..']),
  ',': body([E, E, E, E, '..#..', '.#...']),
  "'": body(['..#..', '..#..', E, E, E, E]),
  '-': body([E, E, '.###.', E, E, E]),
  ':': body([E, '..#..', E, E, '..#..', E]),
};
const ORDER = [' ', ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'Å', 'Ä', 'Ö', ...'0123456789', '!', '?', '.', ',', "'", '-', ':'];

/** Bo's bubble lines shown in turn in the scene */
const LINES = ['SÅG DU?!', 'KOLLA!', 'POMMES!', 'JAG GJORDE DET!', 'MIN BRÄDA!', 'OJ!', 'SNÖ OCH IS!'];
/** labels on the character sheet: asm label -> text */
const LABELS: Record<string, string> = {
  t_bo: 'BO',
  t_apple_bo: 'ÄPPEL-BO',
  t_in_game: 'I SPELET:',
  t_signature: 'BOS SIGNATUR',
  t_push: 'PUSH',
  t_fast: 'FART',
  t_brake: 'BROMS',
  t_look: 'TITTAR',
  t_balance: 'BALANS',
  t_pop: 'POPP',
};

const encode = (s: string) =>
  [...s].map((c) => {
    const k = ORDER.indexOf(c);
    if (k < 0) throw new Error(`no glyph for ${JSON.stringify(c)} in ${JSON.stringify(s)}`);
    return k;
  });

const out = [
  '; GENERATED by games/bo/mockup/gen.ts — do not edit. Bubble font (1 bit per pixel, 8 bytes per glyph)',
  '; and the mockup texts as glyph indices (index = position in the font table); 255 ends a string.',
  '',
  `FONT_GLYPHS = ${ORDER.length}`,
  '',
  '.data',
  'font1:',
];
for (const ch of ORDER) {
  const rows = GLYPHS[ch];
  if (!rows || rows.length !== 8 || rows.some((r) => !/^[.#]{5}$/.test(r))) throw new Error(`bad glyph ${ch}`);
  out.push(`; '${ch}'`);
  for (const r of rows) out.push(`    .byte 0b${r.replace(/#/g, '1').replace(/\./g, '0')}000   ; ${r}`);
}
out.push('', 'lines:', ...LINES.map((_, i) => `    .word line_${i}`), `NUM_LINES = ${LINES.length}`);
LINES.forEach((s, i) => out.push(`line_${i}: .byte ${[...encode(s), 255].join(', ')}   ; ${s}`));
out.push('');
for (const [label, s] of Object.entries(LABELS)) out.push(`${label}: .byte ${[...encode(s), 255].join(', ')}   ; ${s}`);

const file = join(dirname(fileURLToPath(import.meta.url)), 'font.gen.asm');
writeFileSync(file, out.join('\n') + '\n');
console.log(`${file}: ${ORDER.length} glyphs (${ORDER.length * 8} bytes), ${LINES.length} lines, ${Object.keys(LABELS).length} labels`);
