// npm run bench:fountain -> bench/fountain.md
// Model: the sender emits seeds 0,1,2,... (an endless stream); each packet is lost independently with
// probability `loss`. A trial succeeds when the decoder has reconstructed the input AND the SHA-256
// check passed (FountainDecoder only reports done after verifying). We record how many packets were
// *transmitted* until then; percentiles over trials give "packets needed for p % success".
import { writeFileSync } from 'node:fs';
import { FountainDecoder, FountainEncoder, Mode, toHex } from '@qrc/transport';
import { randomBytes, rng } from '../test/helpers/rng';

const Ks = [32, 64, 128, 256];
const LOSSES = [0, 0.1, 0.2, 0.3, 0.4];
const TRIALS = Number(process.env.TRIALS ?? 100);
const BLOCK = 16; // decodability does not depend on block size; small blocks keep the benchmark fast
const SEED = Number(process.env.QRC_SEED ?? 424242);

function trial(K: number, loss: number, mode: Mode, seed: number, gaussian: boolean) {
  const data = randomBytes(seed, K * BLOCK);
  const enc = new FountainEncoder(data, { blockSize: BLOCK, mode });
  const dec = new FountainDecoder({ gaussian });
  const r = rng(seed ^ 0x5bd1e995);
  // Random seed offset so trials sample the code ensemble instead of replaying seeds 0,1,2,... every time.
  const offset = Math.floor(r() * 2 ** 24);
  let sent = 0;
  while (!dec.done) {
    const i = sent++;
    const pkt = enc.packet(mode === Mode.LT ? offset + i : i < K ? i : K + offset + i);
    if (r() >= loss) dec.receive(pkt);
    if (sent > 50 * K) {
      if (gaussian) throw new Error(`no decode after ${sent} packets (seed ${seed})`);
      return { sent: Infinity, received: Infinity }; // peeling-only comparison: count as failure
    }
  }
  if (toHex(dec.getResult()!) !== toHex(data)) throw new Error(`wrong output (seed ${seed})`);
  return { sent, received: dec.received };
}

function pct(sorted: number[], p: number) {
  return sorted[Math.min(sorted.length - 1, Math.ceil(p * sorted.length) - 1)]!;
}
const ovh = (n: number, K: number) => (Number.isFinite(n) ? `${(((n - K) / K) * 100).toFixed(0)} %` : 'fail (>50·K)');

type Row = { K: number; loss: number; mode: Mode; gaussian: boolean; p50: number; p90: number; p99: number; recv99: number };
const rows: Row[] = [];
const t0 = Date.now();
for (const gaussian of [true, false]) {
  for (const mode of [Mode.Systematic, Mode.LT]) {
    for (const K of Ks) {
      for (const loss of gaussian ? LOSSES : [0, 0.2]) {
        const sent: number[] = [];
        const recv: number[] = [];
        for (let t = 0; t < TRIALS; t++) {
          const r = trial(K, loss, mode, SEED + K * 1000 + t + Math.round(loss * 100) * 100000, gaussian);
          sent.push(r.sent);
          recv.push(r.received);
        }
        sent.sort((a, b) => a - b);
        recv.sort((a, b) => a - b);
        rows.push({ K, loss, mode, gaussian, p50: pct(sent, 0.5), p90: pct(sent, 0.9), p99: pct(sent, 0.99), recv99: pct(recv, 0.99) });
        process.stdout.write('.');
      }
    }
  }
}
console.log(`\n${((Date.now() - t0) / 1000).toFixed(1)} s`);

let md = `# Fountain benchmark (layer 1)

Generated by \`npm run bench:fountain\` (seed ${SEED}, ${TRIALS} trials per cell). Do not edit by hand.

**Model.** Sender emits an endless packet stream (LT: seeds offset+0, offset+1, …; systematic: source
seeds 0…K−1 then repair seeds from K+offset; offset random per trial so trials sample the code ensemble); each packet is lost independently with the given probability.
A trial *succeeds* when the decoder has fully reconstructed the input **and** the SHA-256 check passed
(never "fraction of blocks recovered"). Numbers are **packets transmitted** until success, shown as
overhead over K: the p-th percentile over trials = packets needed for p % decode success.
"recv p99" is the number of packets actually *received* at the 99th percentile (loss excluded).

Robust soliton parameters: c = 0.1, δ = 0.5. Systematic repair packets use degree max(d, ⌈K/2⌉) (D-003).\nTheoretical floor with loss L (perfect code): overhead = 1/(1−L) − 1 → 0 / 11 / 25 / 43 / 67 %.

`;
for (const gaussian of [true, false]) {
  md += gaussian
    ? `## Decoder as shipped: peeling + Gaussian-elimination fallback\n\n`
    : `## For comparison: peeling only (no Gaussian elimination)\n\n`;
  md += `| mode | K | loss | 50 % | 90 % | 99 % | recv p99 |\n|---|---:|---:|---:|---:|---:|---:|\n`;
  for (const r of rows.filter((x) => x.gaussian === gaussian)) {
    md += `| ${Mode[r.mode]} | ${r.K} | ${r.loss * 100} % | ${ovh(r.p50, r.K)} | ${ovh(r.p90, r.K)} | ${ovh(r.p99, r.K)} | ${ovh(r.recv99, r.K)} |\n`;
  }
  md += '\n';
}
md += `## Conclusion (see DECISIONS.md D-003)

Default mode: **Systematic** (source blocks first, then dense repair packets), decoded by peeling +
Gaussian elimination. It is at or below pure LT in every cell, is optimal with no loss, and tracks the
theoretical floor within a few percent at K ≥ 128. Pure LT keeps a long p99 tail at small K (blocks
never covered by low-degree packets). Dense repair packets require the Gaussian fallback: with peeling
alone systematic mode fails under loss, which is why the fallback is always on in the shipped decoder.
`;
writeFileSync(new URL('./fountain.md', import.meta.url), md);
console.log(md);
