// npm run bench:qr -> bench/qr.md
import { writeFileSync } from 'node:fs';
import { DEFAULT_FRAME_MS, LEVELS, blockSizeFor, distort, qrByteCapacity, renderQr, type Ecc, type LevelName } from '@qrc/qr';
import { FountainDecoder, FountainEncoder, Mode } from '@qrc/transport';
import { randomBytes, rng } from '../test/helpers/rng';
import { loadDecoders, type DecoderName } from '../test/helpers/decoders';

const TRIALS = Number(process.env.TRIALS ?? 30);
const SEED = Number(process.env.QRC_SEED ?? 5150);
const VERSIONS = [10, 11, 12, 13, 14, 15];
const ECCS: Ecc[] = ['L', 'M', 'Q'];
const LEVEL_NAMES = Object.keys(LEVELS) as LevelName[];

const decoders = await loadDecoders();
type Cell = { ok: number; n: number; ms: number };
const results = new Map<string, Cell>();
const key = (d: string, v: number, e: string, l: string) => `${d}|${v}|${e}|${l}`;
const t0 = Date.now();

for (const v of VERSIONS) {
  for (const e of ECCS) {
    for (const l of LEVEL_NAMES) {
      for (let t = 0; t < TRIALS; t++) {
        const seed = SEED + v * 100000 + ECCS.indexOf(e) * 10000 + LEVEL_NAMES.indexOf(l) * 1000 + t;
        const payload = randomBytes(seed, qrByteCapacity(v, e));
        const img = distort(renderQr(payload, { version: v, ecc: e }), LEVELS[l], seed);
        for (const [name, dec] of Object.entries(decoders) as [DecoderName, (typeof decoders)[DecoderName]][]) {
          const c = results.get(key(name, v, e, l)) ?? { ok: 0, n: 0, ms: 0 };
          const s = performance.now();
          const out = await dec(img.rgba, img.width, img.height);
          c.ms += performance.now() - s;
          c.n++;
          if (out && out.length === payload.length && out.every((b, i) => b === payload[i])) c.ok++;
          results.set(key(name, v, e, l), c);
        }
      }
      process.stdout.write('.');
    }
  }
}
console.log(`\n${((Date.now() - t0) / 1000).toFixed(0)} s`);

const pct = (c: Cell) => `${Math.round((100 * c.ok) / c.n)} %`;
let md = `# QR benchmark (layers 2–3)

Generated by \`npm run bench:qr\` (seed ${SEED}, ${TRIALS} frames per cell). Do not edit by hand.

Each frame: a random payload filling the symbol's byte-mode capacity, rendered at 4 px/module with a
4-module quiet zone, then distorted at the given level (definitions: DECISIONS.md D-006, fixed before
measuring). Success = the decoder returned exactly the payload bytes. Decoders run in Node on this machine
(not on a phone): jsQR 1.4; zxing-wasm (reader build, \`tryHarder\`) single pass with its default
LocalAverage binarizer (\`zxing-single\`); and \`zxing\` = LocalAverage, then GlobalHistogram only if the first
pass found nothing (what the scanner ships, D-007).

## Decode success rate

`;
for (const d of Object.keys(decoders)) {
  md += `### ${d}\n\n| version | ECC | capacity (B) | block (B) | ${LEVEL_NAMES.join(' | ')} |\n|---:|---|---:|---:|${LEVEL_NAMES.map(() => '---:').join('|')}|\n`;
  for (const v of VERSIONS) for (const e of ECCS) md += `| ${v} | ${e} | ${qrByteCapacity(v, e)} | ${blockSizeFor(v, e)} | ${LEVEL_NAMES.map((l) => pct(results.get(key(d, v, e, l))!)).join(' | ')} |\n`;
  md += '\n';
}
md += `## Mean decode time per frame (ms, this machine, Node)\n\n| decoder | ${LEVEL_NAMES.join(' | ')} |\n|---|${LEVEL_NAMES.map(() => '---:').join('|')}|\n`;
for (const d of Object.keys(decoders)) {
  md += `| ${d} | ${LEVEL_NAMES.map((l) => {
    let ms = 0, n = 0;
    for (const v of VERSIONS) for (const e of ECCS) { const c = results.get(key(d, v, e, l))!; ms += c.ms; n += c.n; }
    return (ms / n).toFixed(1);
  }).join(' | ')} |\n`;
}

// Summary by decoder at moderate, for choosing defaults
md += `\n## Moderate distortion, all versions × ECC\n\n| decoder | overall success | best cell |\n|---|---:|---|\n`;
for (const d of Object.keys(decoders)) {
  let ok = 0, n = 0, best = '', bestRate = -1;
  for (const v of VERSIONS) for (const e of ECCS) {
    const c = results.get(key(d, v, e, 'moderate'))!;
    ok += c.ok; n += c.n;
    const rate = c.ok / c.n + qrByteCapacity(v, e) / 1e6; // tie-break on capacity
    if (rate > bestRate) { bestRate = rate; best = `v${v}-${e} ${pct(c)}`; }
  }
  md += `| ${d} | ${Math.round((100 * ok) / n)} % | ${best} |\n`;
}

// ---- transfer estimate for a 50 KB cartridge with the defaults --------------------------------
const V = Number(process.env.EST_VERSION ?? 12);
const E = (process.env.EST_ECC ?? 'M') as Ecc;
const FRAME_MS = DEFAULT_FRAME_MS;
const B = blockSizeFor(V, E);
const size = 50 * 1024;
const K = Math.ceil(size / B);
md += `\n## Transfer estimate: 50 KB cartridge, v${V}-${E}, ${FRAME_MS} ms/frame, 20 % frame loss\n\n`;
md += `Blocks: K = ⌈${size} / ${B}⌉ = **${K}**. The GIF loops over N distinct frames (systematic: K source + N−K repair).\n`;
md += `Simulation: frames shown in loop order, each captured independently with probability 0.8, until the\n`;
md += `decoder has reconstructed and verified the data (100 trials).\n\n`;
md += `| frames in loop N | p50 frames shown | p90 | p99 | p90 seconds | effective KB/s at p90 |\n|---:|---:|---:|---:|---:|---:|\n`;
const data = randomBytes(SEED, size);
for (const extra of [0.1, 0.25, 0.5, 1.0]) {
  const N = K + Math.max(4, Math.ceil(K * extra));
  const enc = new FountainEncoder(data, { blockSize: B, mode: Mode.Systematic });
  const packets = Array.from({ length: N }, (_, i) => enc.packet(i));
  const shown: number[] = [];
  for (let t = 0; t < 100; t++) {
    const r = rng(SEED + t);
    const dec = new FountainDecoder();
    let n = Math.floor(r() * N); // camera starts at a random point of the loop
    const start = n;
    while (!dec.done) {
      if (r() >= 0.2) dec.receive(packets[n % N]!);
      n++;
    }
    shown.push(n - start);
  }
  shown.sort((a, b) => a - b);
  const p = (q: number) => shown[Math.ceil(q * shown.length) - 1]!;
  const sec = (p(0.9) * FRAME_MS) / 1000;
  md += `| ${N} (K + ${Math.round(extra * 100)} %) | ${p(0.5)} | ${p(0.9)} | ${p(0.99)} | ${sec.toFixed(1)} | ${(size / 1024 / sec).toFixed(2)} |\n`;
}
md += `\nPayload per frame: ${B} bytes of cartridge data (${qrByteCapacity(V, E)} − 25 bytes packet overhead). `;
md += `At ${FRAME_MS} ms/frame the raw ceiling is ${((B * 1000) / FRAME_MS / 1024).toFixed(2)} KB/s.\n`;
writeFileSync(new URL('./qr.md', import.meta.url), md);
console.log(md);
