; GENERATED by games/blackbox/tools/tiles.ts — do not edit.

A_SOLID = 1
A_OPAQUE = 2
A_USE = 4
NUM_TILESETS = 4

.data
tile_attr:
    .byte 0, 3, 3, 3, 3, 1, 0, 3, 2, 5, 5, 7, 5
floor_colors:
    .byte 1, 3, 3, 0
tileset_ptrs:
    .word tiles_OFFICE - 32, tiles_SECURITY - 32, tiles_BUNKER - 32, tiles_SERVER - 32
tiles_OFFICE:
.sprite   ; WALL
    33333333
    33333333
    33373333
    33333333
    33333333
    33333373
    33333333
    33333333
.sprite   ; WALLFACE
    33333333
    aaaaaaaa
    77777777
    77777777
    77737777
    77777777
    77777777
    33333333
.sprite   ; SHELF
    33333333
    388c88c3
    33333333
    3c88c883
    33333333
    38c88c83
    33333333
    33333333
.sprite   ; CAMERA
    33333333
    33777733
    37aaaa73
    37a66a73
    37aaaa73
    33777733
    33377333
    33333333
.sprite   ; DESK
    ........
    44444444
    49999994
    49999994
    49999994
    44444444
    4......4
    ........
.sprite   ; DOOR
    3......3
    3......3
    3......3
    3......3
    3......3
    3......3
    3......3
    3......3
.sprite   ; LOCKED
    33333333
    36666663
    36.66.63
    36666663
    366ee663
    36666663
    36666663
    33333333
.sprite   ; VENT
    33333333
    33a3a3a3
    33a3a3a3
    33a3a3a3
    33a3a3a3
    33a3a3a3
    33a3a3a3
    33333333
.sprite   ; TERMINAL
    33333333
    30000003
    30bb0b03
    30b0bb03
    30000003
    33333333
    .373373.
    .777777.
.sprite   ; CHARGER
    .888888.
    8dddddd8
    8d8888d8
    8d8ee8d8
    8d8888d8
    8dddddd8
    .888888.
    ........
.sprite   ; LIFT
    77777777
    7aaaaaa7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7aaaaaa7
    77777777
.sprite   ; CABLE
    ........
    ..eeee..
    .e....e.
    .e.33.e.
    .e.33.e.
    ..e..e..
    ...ee...
    ....e...
tiles_SECURITY:
.sprite   ; WALL
    77777777
    77777777
    777a7777
    77777777
    77777777
    777777a7
    77777777
    77777777
.sprite   ; WALLFACE
    77777777
    ffffffff
    aaaaaaaa
    aaaaaaaa
    aaa7aaaa
    aaaaaaaa
    aaaaaaaa
    77777777
.sprite   ; SHELF
    77777777
    7ddbddb7
    77777777
    7bddbdd7
    77777777
    7dbddbd7
    77777777
    77777777
.sprite   ; CAMERA
    77777777
    77aaaa77
    7affffa7
    7af66fa7
    7affffa7
    77aaaa77
    777aa777
    77777777
.sprite   ; DESK
    ........
    44444444
    49999994
    49999994
    49999994
    44444444
    4......4
    ........
.sprite   ; DOOR
    7......7
    7......7
    7......7
    7......7
    7......7
    7......7
    7......7
    7......7
.sprite   ; LOCKED
    77777777
    76666667
    76.66.67
    76666667
    766ee667
    76666667
    76666667
    77777777
.sprite   ; VENT
    77777777
    73f3f3f7
    73f3f3f7
    73f3f3f7
    73f3f3f7
    73f3f3f7
    73f3f3f7
    77777777
.sprite   ; TERMINAL
    33333333
    30000003
    30bb0b03
    30b0bb03
    30000003
    33333333
    .373373.
    .777777.
.sprite   ; CHARGER
    .888888.
    8dddddd8
    8d8888d8
    8d8ee8d8
    8d8888d8
    8dddddd8
    .888888.
    ........
.sprite   ; LIFT
    77777777
    7aaaaaa7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7aaaaaa7
    77777777
.sprite   ; CABLE
    ........
    ..eeee..
    .e....e.
    .e.33.e.
    .e.33.e.
    ..e..e..
    ...ee...
    ....e...
tiles_BUNKER:
.sprite   ; WALL
    44444444
    44444444
    44474444
    44444444
    44444444
    44444474
    44444444
    44444444
.sprite   ; WALLFACE
    44444444
    cccccccc
    77777777
    77777777
    77747777
    77777777
    77777777
    44444444
.sprite   ; SHELF
    44444444
    499e99e4
    44444444
    4e99e994
    44444444
    49e99e94
    44444444
    44444444
.sprite   ; CAMERA
    44444444
    44777744
    47cccc74
    47c66c74
    47cccc74
    44777744
    44477444
    44444444
.sprite   ; DESK
    ........
    44444444
    49999994
    49999994
    49999994
    44444444
    4......4
    ........
.sprite   ; DOOR
    4......4
    4......4
    4......4
    4......4
    4......4
    4......4
    4......4
    4......4
.sprite   ; LOCKED
    44444444
    46666664
    46.66.64
    46666664
    466ee664
    46666664
    46666664
    44444444
.sprite   ; VENT
    44444444
    43c3c3c4
    43c3c3c4
    43c3c3c4
    43c3c3c4
    43c3c3c4
    43c3c3c4
    44444444
.sprite   ; TERMINAL
    33333333
    30000003
    30bb0b03
    30b0bb03
    30000003
    33333333
    .373373.
    .777777.
.sprite   ; CHARGER
    .888888.
    8dddddd8
    8d8888d8
    8d8ee8d8
    8d8888d8
    8dddddd8
    .888888.
    ........
.sprite   ; LIFT
    77777777
    7aaaaaa7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7aaaaaa7
    77777777
.sprite   ; CABLE
    ........
    ..eeee..
    .e....e.
    .e.33.e.
    .e.33.e.
    ..e..e..
    ...ee...
    ....e...
tiles_SERVER:
.sprite   ; WALL
    22222222
    22222222
    22282222
    22222222
    22222222
    22222282
    22222222
    22222222
.sprite   ; WALLFACE
    22222222
    dddddddd
    88888888
    88888888
    88828888
    88888888
    88888888
    22222222
.sprite   ; SHELF
    22222222
    2bb6bb62
    22222222
    26bb6bb2
    22222222
    2b6bb6b2
    22222222
    22222222
.sprite   ; CAMERA
    22222222
    22888822
    28dddd82
    28d66d82
    28dddd82
    22888822
    22288222
    22222222
.sprite   ; DESK
    ........
    44444444
    49999994
    49999994
    49999994
    44444444
    4......4
    ........
.sprite   ; DOOR
    2......2
    2......2
    2......2
    2......2
    2......2
    2......2
    2......2
    2......2
.sprite   ; LOCKED
    22222222
    26666662
    26.66.62
    26666662
    266ee662
    26666662
    26666662
    22222222
.sprite   ; VENT
    22222222
    23d3d3d2
    23d3d3d2
    23d3d3d2
    23d3d3d2
    23d3d3d2
    23d3d3d2
    22222222
.sprite   ; TERMINAL
    33333333
    30000003
    30bb0b03
    30b0bb03
    30000003
    33333333
    .373373.
    .777777.
.sprite   ; CHARGER
    .888888.
    8dddddd8
    8d8888d8
    8d8ee8d8
    8d8888d8
    8dddddd8
    .888888.
    ........
.sprite   ; LIFT
    77777777
    7aaaaaa7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7a7aa7a7
    7aaaaaa7
    77777777
.sprite   ; CABLE
    ........
    ..eeee..
    .e....e.
    .e.33.e.
    .e.33.e.
    ..e..e..
    ...ee...
    ....e...
