; GENERATED by games/bo/tools/levels.ts from levels/*.lvl — do not edit.
; Level table (DESIGN.md §14.1): per level terrain, objects, width, start height, rows, world, start column,
; music, name. Terrain: one byte per segment (type << 5 | length - 1). Objects: col lo, col hi | type << 1,
; row, param [, extra]; 255 255 ends the list.

NUM_LEVELS = 3
LV_T1 = 0
LV_T2 = 1
LV_T3 = 2
OT_TILE = 1
OT_RECT = 2
OT_APPLES = 3
OT_BOX = 4
OT_STAR = 5
OT_PART = 6
OT_FLAG = 7
OT_GOAL = 8
OT_ENEMY = 9
OT_FG = 10
OT_RAMP = 11
OT_RAILD = 12
OT_PLATFORM = 13
OT_SIGN = 14
OT_PICKUP = 15
OT_PREFAB = 16
SP_MAT_NORMAL = 16
SP_MAT_SAND = 17
SP_MAT_ICE = 18
SP_MAT_ALT = 19
SP_LIQ_WATER = 20
SP_LIQ_CHOC = 21
SP_END = 31
EN_SNAIL = 1
NUM_PREFABS = 7

.data
level_table:
    .word lv_T1_ter, lv_T1_obj, 164
    .byte 4, 16, 1, 3, 0, 0
    .word lv_T2_ter, lv_T2_obj, 236
    .byte 22, 32, 1, 3, 0, 0
    .word lv_T3_ter, lv_T3_obj, 370
    .byte 22, 32, 1, 3, 0, 0
lv_T1_ter:   ; T1 TESTBANA 1
    .byte 31, 23, 233, 15, 231, 29, 234, 11, 230, 31, 9, 194, 4, 255
lv_T1_obj:
    .byte 6, 28, 27, 0, 36, 2, 27, 14, 44, 32, 27, 1, 50, 4, 27, 14, 17, 80, 4, 27, 14, 32, 81, 4
    .byte 27, 14, 64, 128, 4, 24, 14, 3, 150, 2, 27, 14, 153, 14, 27, 0, 255, 255
lv_T2_ter:   ; T2 TESTBANA 2
    .byte 9, 71, 3, 39, 7, 135, 3, 101, 7, 69, 31, 31, 31, 3, 131, 31, 7, 255
lv_T2_obj:
    .byte 160, 26, 15, 6, 170, 26, 13, 5, 178, 26, 15, 4, 186, 4, 17, 14, 1, 255, 255
lv_T3_ter:   ; T3 TESTBANA 3
    .byte 31, 5, 69, 21, 37, 69, 29, 37, 69, 15, 37, 69, 21, 37, 69, 31, 1, 131, 7, 241, 9, 240, 5, 66, 242, 31, 3, 240, 5, 194, 5, 162, 11, 255
lv_T3_obj:
    .byte 12, 22, 9, 0, 22, 22, 9, 32, 50, 22, 15, 0, 96, 22, 15, 0, 150, 22, 15, 0, 190, 22, 15, 0
    .byte 236, 22, 15, 32, 6, 15, 15, 0, 8, 5, 15, 33, 5, 14, 25, 15, 131, 21, 3, 19, 18, 32, 7, 19
    .byte 1, 84, 15, 22, 0, 85, 3, 22, 15, 88, 9, 22, 1, 94, 15, 22, 0, 110, 17, 22, 0, 255, 255
prefab_table:
    .word pf_house, pf_bin, pf_bins2, pf_fence, pf_garage, pf_tree, pf_hedge
pf_house:
    .byte 6, 6
    .byte 0, 72, 73, 73, 74, 0
    .byte 72, 73, 73, 73, 73, 74
    .byte 0, 75, 68, 68, 76, 0
    .byte 0, 75, 69, 69, 76, 0
    .byte 0, 75, 70, 68, 76, 0
    .byte 0, 75, 71, 68, 76, 0
pf_bin:
    .byte 1, 2
    .byte 66
    .byte 67
pf_bins2:
    .byte 2, 2
    .byte 66, 66
    .byte 67, 67
pf_fence:
    .byte 4, 2
    .byte 77, 77, 77, 77
    .byte 78, 78, 78, 78
pf_garage:
    .byte 7, 3
    .byte 83, 83, 83, 83, 83, 83, 83
    .byte 84, 82, 82, 82, 82, 82, 84
    .byte 84, 82, 82, 82, 82, 82, 84
pf_tree:
    .byte 3, 3
    .byte 86, 86, 86
    .byte 0, 85, 0
    .byte 0, 85, 0
pf_hedge:
    .byte 6, 3
    .byte 81, 81, 81, 81, 81, 81
    .byte 81, 81, 81, 81, 81, 81
    .byte 81, 81, 81, 81, 81, 81
