; GENERATED by games/bo/tools/text.ts — do not edit. Bubble font (1 bit per pixel, 8 bytes per glyph) and every
; text as glyph indices (index = position in the font table); 255 ends a text, 254 starts its second row.

FONT_GLYPHS = 48
NUM_TEXTS = 52
TX_SKRIII = 0   ; SKRIII!
TX_NEJ_MINA_POMMES = 1   ; NEJ! MINA POMMES!
TX_VANTA_MASEN = 2   ; VÄNTA, MÅSEN!
TX_MINA_POMMES = 3   ; MINA POMMES!
TX_MUMS = 4   ; MUMS!
TX_GODISLANDET = 5   ; GODISLANDET →
TX_JAG_SKA_TILL_GODISLANDET = 6   ; JAG SKA TILL GODISLANDET!
TX_DEN_VILLE_BARA_HA_MOROTTER = 7   ; DEN VILLE BARA HA MORÖTTER!
TX_DEN_AR_AVSTANGD = 8   ; DEN ÄR AVSTÄNGD!
TX_JAG_GJORDE_DET = 9   ; JAG GJORDE DET!
TX_NEJ_MIN_BRADA = 10   ; NEJ! MIN BRÄDA!
TX_LANA_MIN = 11   ; LÅNA MIN!
TX_EN_LAKRITSBRADA = 12   ; EN LAKRITSBRÄDA!
TX_MIN_BRADA = 13   ; MIN BRÄDA!
TX_VILL_DU_HA_POMMES = 14   ; VILL DU HA POMMES?
TX_SKRII = 15   ; SKRII!
TX_SLUT = 16   ; SLUT
TX_AJ = 17   ; AJ!
TX_OJ = 18   ; OJ!
TX_POMMES = 19   ; POMMES!
TX_POMMES_POWER = 20   ; POMMES POWER!
TX_GODIS = 21   ; GODIS!
TX_APPELHJALM = 22   ; ÄPPELHJÄLM!
TX_KOLLA = 23   ; KOLLA!
TX_SAG_DU = 24   ; SÅG DU?!
TX_WIII = 25   ; WIII!
TX_EN_STJARNA = 26   ; EN STJÄRNA!
TX_ETT_HJUL = 27   ; ETT HJUL!
TX_TRUCKAR = 28   ; TRUCKAR!
TX_EN_DESIGN = 29   ; EN DESIGN!
TX_ETT_MARKE = 30   ; ETT MÄRKE!
TX_ETT_LIV_TILL = 31   ; ETT LIV TILL!
TX_EN_NY_BRADA = 32   ; EN NY BRÄDA!
TX_FORSOK_IGEN = 33   ; FÖRSÖK IGEN!
TX_SUPERBOSSE = 34   ; SUPERBOSSE!
TX_POFF = 35   ; POFF
TX_ZZZ = 36   ; ZZZ
TX_SPLAT = 37   ; SPLAT
TX_FEL_KOD = 38   ; FEL KOD
TX_BO_S = 39   ; BO'S
TX_SKATEAVENTYR = 40   ; SKATEÄVENTYR
TX_BANA = 41   ; BANA
TX_STJARNOR = 42   ; STJÄRNOR
TX_APPLEN = 43   ; ÄPPLEN
TX_POANG = 44   ; POÄNG
TX_DEL = 45   ; DEL
TX_KOD = 46   ; KOD
TX_TESTBANA_1 = 47   ; TESTBANA 1
TX_TESTBANA_2 = 48   ; TESTBANA 2
TX_TESTBANA_3 = 49   ; TESTBANA 3
TX_TESTBANA_4 = 50   ; TESTBANA 4
TX_TESTBANA_5 = 51   ; TESTBANA 5

.data
font1:
    .byte $00, $00, $00, $00, $00, $00, $00, $00   ; ' '
    .byte $00, $00, $70, $88, $88, $f8, $88, $88   ; 'A'
    .byte $00, $00, $f0, $88, $f0, $88, $88, $f0   ; 'B'
    .byte $00, $00, $70, $88, $80, $80, $88, $70   ; 'C'
    .byte $00, $00, $f0, $88, $88, $88, $88, $f0   ; 'D'
    .byte $00, $00, $f8, $80, $f0, $80, $80, $f8   ; 'E'
    .byte $00, $00, $f8, $80, $f0, $80, $80, $80   ; 'F'
    .byte $00, $00, $70, $80, $b8, $88, $88, $70   ; 'G'
    .byte $00, $00, $88, $88, $f8, $88, $88, $88   ; 'H'
    .byte $00, $00, $70, $20, $20, $20, $20, $70   ; 'I'
    .byte $00, $00, $38, $10, $10, $10, $90, $60   ; 'J'
    .byte $00, $00, $88, $90, $e0, $90, $88, $88   ; 'K'
    .byte $00, $00, $80, $80, $80, $80, $80, $f8   ; 'L'
    .byte $00, $00, $88, $d8, $a8, $88, $88, $88   ; 'M'
    .byte $00, $00, $88, $c8, $a8, $98, $88, $88   ; 'N'
    .byte $00, $00, $70, $88, $88, $88, $88, $70   ; 'O'
    .byte $00, $00, $f0, $88, $88, $f0, $80, $80   ; 'P'
    .byte $00, $00, $70, $88, $88, $a8, $90, $68   ; 'Q'
    .byte $00, $00, $f0, $88, $88, $f0, $90, $88   ; 'R'
    .byte $00, $00, $78, $80, $70, $08, $08, $f0   ; 'S'
    .byte $00, $00, $f8, $20, $20, $20, $20, $20   ; 'T'
    .byte $00, $00, $88, $88, $88, $88, $88, $70   ; 'U'
    .byte $00, $00, $88, $88, $88, $88, $50, $20   ; 'V'
    .byte $00, $00, $88, $88, $88, $a8, $d8, $88   ; 'W'
    .byte $00, $00, $88, $50, $20, $20, $50, $88   ; 'X'
    .byte $00, $00, $88, $88, $50, $20, $20, $20   ; 'Y'
    .byte $00, $00, $f8, $10, $20, $40, $80, $f8   ; 'Z'
    .byte $20, $50, $20, $70, $88, $f8, $88, $88   ; 'Å'
    .byte $00, $50, $00, $70, $88, $f8, $88, $88   ; 'Ä'
    .byte $00, $50, $00, $70, $88, $88, $88, $70   ; 'Ö'
    .byte $00, $00, $70, $98, $a8, $c8, $88, $70   ; '0'
    .byte $00, $00, $20, $60, $20, $20, $20, $70   ; '1'
    .byte $00, $00, $70, $88, $10, $20, $40, $f8   ; '2'
    .byte $00, $00, $f0, $08, $70, $08, $08, $f0   ; '3'
    .byte $00, $00, $10, $30, $50, $f8, $10, $10   ; '4'
    .byte $00, $00, $f8, $80, $f0, $08, $08, $f0   ; '5'
    .byte $00, $00, $70, $80, $f0, $88, $88, $70   ; '6'
    .byte $00, $00, $f8, $08, $10, $20, $20, $20   ; '7'
    .byte $00, $00, $70, $88, $70, $88, $88, $70   ; '8'
    .byte $00, $00, $70, $88, $88, $78, $08, $70   ; '9'
    .byte $00, $00, $20, $20, $20, $20, $00, $20   ; '!'
    .byte $00, $00, $70, $88, $10, $20, $00, $20   ; '?'
    .byte $00, $00, $00, $00, $00, $00, $00, $20   ; '.'
    .byte $00, $00, $00, $00, $00, $00, $20, $40   ; ','
    .byte $00, $00, $20, $20, $00, $00, $00, $00   ; '''
    .byte $00, $00, $00, $00, $70, $00, $00, $00   ; '-'
    .byte $00, $00, $00, $20, $00, $00, $20, $00   ; ':'
    .byte $00, $00, $00, $10, $f8, $10, $00, $00   ; '→'
text_table:
    .word tx_0, tx_1, tx_2, tx_3, tx_4, tx_5, tx_6, tx_7
    .word tx_8, tx_9, tx_10, tx_11, tx_12, tx_13, tx_14, tx_15
    .word tx_16, tx_17, tx_18, tx_19, tx_20, tx_21, tx_22, tx_23
    .word tx_24, tx_25, tx_26, tx_27, tx_28, tx_29, tx_30, tx_31
    .word tx_32, tx_33, tx_34, tx_35, tx_36, tx_37, tx_38, tx_39
    .word tx_40, tx_41, tx_42, tx_43, tx_44, tx_45, tx_46, tx_47
    .word tx_48, tx_49, tx_50, tx_51
tx_0: .byte 19, 11, 18, 9, 9, 9, 40, 255   ; SKRIII!
tx_1: .byte 14, 5, 10, 40, 0, 13, 9, 14, 1, 0, 16, 15, 13, 13, 5, 19, 40, 255   ; NEJ! MINA POMMES!
tx_2: .byte 22, 28, 14, 20, 1, 43, 0, 13, 27, 19, 5, 14, 40, 255   ; VÄNTA, MÅSEN!
tx_3: .byte 13, 9, 14, 1, 0, 16, 15, 13, 13, 5, 19, 40, 255   ; MINA POMMES!
tx_4: .byte 13, 21, 13, 19, 40, 255   ; MUMS!
tx_5: .byte 7, 15, 4, 9, 19, 12, 1, 14, 4, 5, 20, 0, 47, 255   ; GODISLANDET →
tx_6: .byte 10, 1, 7, 0, 19, 11, 1, 0, 20, 9, 12, 12, 254, 7, 15, 4, 9, 19, 12, 1, 14, 4, 5, 20, 40, 255   ; JAG SKA TILL GODISLANDET!
tx_7: .byte 4, 5, 14, 0, 22, 9, 12, 12, 5, 0, 2, 1, 18, 1, 0, 8, 1, 254, 13, 15, 18, 29, 20, 20, 5, 18, 40, 255   ; DEN VILLE BARA HA MORÖTTER!
tx_8: .byte 4, 5, 14, 0, 28, 18, 0, 1, 22, 19, 20, 28, 14, 7, 4, 40, 255   ; DEN ÄR AVSTÄNGD!
tx_9: .byte 10, 1, 7, 0, 7, 10, 15, 18, 4, 5, 0, 4, 5, 20, 40, 255   ; JAG GJORDE DET!
tx_10: .byte 14, 5, 10, 40, 0, 13, 9, 14, 0, 2, 18, 28, 4, 1, 40, 255   ; NEJ! MIN BRÄDA!
tx_11: .byte 12, 27, 14, 1, 0, 13, 9, 14, 40, 255   ; LÅNA MIN!
tx_12: .byte 5, 14, 0, 12, 1, 11, 18, 9, 20, 19, 2, 18, 28, 4, 1, 40, 255   ; EN LAKRITSBRÄDA!
tx_13: .byte 13, 9, 14, 0, 2, 18, 28, 4, 1, 40, 255   ; MIN BRÄDA!
tx_14: .byte 22, 9, 12, 12, 0, 4, 21, 0, 8, 1, 0, 16, 15, 13, 13, 5, 19, 41, 255   ; VILL DU HA POMMES?
tx_15: .byte 19, 11, 18, 9, 9, 40, 255   ; SKRII!
tx_16: .byte 19, 12, 21, 20, 255   ; SLUT
tx_17: .byte 1, 10, 40, 255   ; AJ!
tx_18: .byte 15, 10, 40, 255   ; OJ!
tx_19: .byte 16, 15, 13, 13, 5, 19, 40, 255   ; POMMES!
tx_20: .byte 16, 15, 13, 13, 5, 19, 0, 16, 15, 23, 5, 18, 40, 255   ; POMMES POWER!
tx_21: .byte 7, 15, 4, 9, 19, 40, 255   ; GODIS!
tx_22: .byte 28, 16, 16, 5, 12, 8, 10, 28, 12, 13, 40, 255   ; ÄPPELHJÄLM!
tx_23: .byte 11, 15, 12, 12, 1, 40, 255   ; KOLLA!
tx_24: .byte 19, 27, 7, 0, 4, 21, 41, 40, 255   ; SÅG DU?!
tx_25: .byte 23, 9, 9, 9, 40, 255   ; WIII!
tx_26: .byte 5, 14, 0, 19, 20, 10, 28, 18, 14, 1, 40, 255   ; EN STJÄRNA!
tx_27: .byte 5, 20, 20, 0, 8, 10, 21, 12, 40, 255   ; ETT HJUL!
tx_28: .byte 20, 18, 21, 3, 11, 1, 18, 40, 255   ; TRUCKAR!
tx_29: .byte 5, 14, 0, 4, 5, 19, 9, 7, 14, 40, 255   ; EN DESIGN!
tx_30: .byte 5, 20, 20, 0, 13, 28, 18, 11, 5, 40, 255   ; ETT MÄRKE!
tx_31: .byte 5, 20, 20, 0, 12, 9, 22, 0, 20, 9, 12, 12, 40, 255   ; ETT LIV TILL!
tx_32: .byte 5, 14, 0, 14, 25, 0, 2, 18, 28, 4, 1, 40, 255   ; EN NY BRÄDA!
tx_33: .byte 6, 29, 18, 19, 29, 11, 0, 9, 7, 5, 14, 40, 255   ; FÖRSÖK IGEN!
tx_34: .byte 19, 21, 16, 5, 18, 2, 15, 19, 19, 5, 40, 255   ; SUPERBOSSE!
tx_35: .byte 16, 15, 6, 6, 255   ; POFF
tx_36: .byte 26, 26, 26, 255   ; ZZZ
tx_37: .byte 19, 16, 12, 1, 20, 255   ; SPLAT
tx_38: .byte 6, 5, 12, 0, 11, 15, 4, 255   ; FEL KOD
tx_39: .byte 2, 15, 44, 19, 255   ; BO'S
tx_40: .byte 19, 11, 1, 20, 5, 28, 22, 5, 14, 20, 25, 18, 255   ; SKATEÄVENTYR
tx_41: .byte 2, 1, 14, 1, 255   ; BANA
tx_42: .byte 19, 20, 10, 28, 18, 14, 15, 18, 255   ; STJÄRNOR
tx_43: .byte 28, 16, 16, 12, 5, 14, 255   ; ÄPPLEN
tx_44: .byte 16, 15, 28, 14, 7, 255   ; POÄNG
tx_45: .byte 4, 5, 12, 255   ; DEL
tx_46: .byte 11, 15, 4, 255   ; KOD
tx_47: .byte 20, 5, 19, 20, 2, 1, 14, 1, 0, 31, 255   ; TESTBANA 1
tx_48: .byte 20, 5, 19, 20, 2, 1, 14, 1, 0, 32, 255   ; TESTBANA 2
tx_49: .byte 20, 5, 19, 20, 2, 1, 14, 1, 0, 33, 255   ; TESTBANA 3
tx_50: .byte 20, 5, 19, 20, 2, 1, 14, 1, 0, 34, 255   ; TESTBANA 4
tx_51: .byte 20, 5, 19, 20, 2, 1, 14, 1, 0, 35, 255   ; TESTBANA 5
level_names:   ; text id of every level, in the level table order
    .byte 47, 48, 49, 50, 51
